directory: 'raw_dataset'
CNN_model: 'LeNet'
dense_model:
  - 16
  - 16
  - 32
optimizer: 'Adam'
LR_scheduler: 'None'
init_lr: 'None'
momentum: 0.05
weight_decay: 0.0001
learning_rate: 0.1
beta: 0.8
mini_batch_size: 10
loss_function: 'mape'
number_of_epochs: 30
train_val_test_split:
  - 0.7
  - 0.15
  - 0.15
image_height: 100
image_width: 100
CNN_input_shape: [240, 240, 3]
train_val_test_ratio: [0.70,0.10,0.20]
augmentation_multiplier: 2
