directory: 'raw_dataset'
CNN_model: 'RegNet'
dense_model:
  - 32
  - 32
optimizer: 'Adam'
LR_scheduler: 'None'
init_lr: 'None'
momentum: 0.05
weight_decay: 0.001
learning_rate: 0.1
learning_rates: [0.005,0.002,0.003,0.004,0.005]
beta: 0.7
mini_batch_size: 32
#loss_function: "mean_absolute_percentage_error"
loss_function: "huber_loss"
number_of_epochs: 200
image_height: 150
image_width: 150
CNN_input_shape: [64, 64, 3]
train_val_test_ratio: [0.70,0.10,0.20]
augmentation_multiplier: 2
import_mode: 'True'

# dense network (64 mape)
# directory: 'raw_dataset'
# CNN_model: 'RegNet'
# dense_model:
#   - 32
#   - 32
#   - 1
# optimizer: 'Adam'
# LR_scheduler: 'None'
# init_lr: 'None'
# momentum: 0.002
# weight_decay: 0.0001
# learning_rate: 0.0001
# learning_rates: [0.001,0.002,0.003,0.004,0.005]
# beta: 0.7
# mini_batch_size: 32
# loss_function: "mean_absolute_percentage_error"
# #loss_function: "mean_squared_error"
# number_of_epochs: 250
# image_height: 150
# image_width: 150
# CNN_input_shape: [64, 64, 3]
# train_val_test_ratio: [0.70,0.10,0.20]
# augmentation_multiplier: 1
# import_mode: 'False' #'True'

