directory: 'raw_dataset'
CNN_model: 'RegNet'
dense_model:
  - 8
  - 4
optimizer: 'Adam'
LR_scheduler: 'None'
init_lr: 'None'
momentum: 0.05
weight_decay: 0.001
learning_rate: 0.1
learning_rates: [0.1,0.002,0.003,0.004,0.005]
beta: 0.7
mini_batch_size: 8
loss_function: "mean_absolute_percentage_error"
number_of_epochs: 100
image_height: 150
image_width: 150
CNN_input_shape: [64, 64, 3]
train_val_test_ratio: [0.70,0.10,0.20]
augmentation_multiplier: 2
import_mode: 'True'
